### ISSUE TITLE
Lowering the bar for Dimensions, especially when constructing Datasets

### ISSUE THREAD

**Issue by ssomnath** [pycroscopy/sidpy#1]
@gduscher - I think that we should continue development of the Dimension class here.

**Comment by ssomnath** [comment]
Requirements for Dimension to be lowered to just the name. . The values will conform to whatever is the size of the dimension on the N-dimensional dataset and and type (spectral / position ....) will default to position

**Comment by ssomnath** [comment]
If the minimum for ``Dimensions`` is just the name, we could in theory accept even strings instead of ``Dimension`` objects when constructing ``Dataset`` objects. Obviously, internally, we would up convert the string to a Dimension object.

**Comment by gduscher** [comment]
Actually at this point the minimal information is name and values. 
We could reduce this to a name and accept strings.

Your comment make me think that the dimensions are not as well integrated as they should be.
May be we should name those dimensions initially by their shape number ('0', '1', '2', ...)  in the beginning and allow them to be named. (just a string). 

Like in dataset.dimensions.0.name = 'x'

Then we can change the dimension properties one by one or all at once with the set_dimension function.

dataset.x.values = dataset.x.values * scale

**Comment by ssomnath** [comment]
I like the idea of naming dimensions by default by their position index. 0, 1, 2, etc. I wonder how we will track dimensions upon operations like a transpose etc.

**Comment by ssomnath** [comment]
I think both the ``Dimension`` and ``Dataset`` have fairly minimal requirements now. Should be OK to close now
