### ISSUE TITLE
update attribute of dataset when changing name od a dimension

### ISSUE THREAD

**Issue by gduscher** [pycroscopy/sidpy#19]

**Comment by gduscher** [comment]
We can now change the name of the dimension attribute of a dataset without the need to set all variables again through (set_dimension). The new function is ``set_dimension_name`` in Dimensions class.
A more elegant way would have been better but will be complicated to implement.

**Comment by ssomnath** [comment]
``rename_dimension()`` would be a shorter method name if you are interested.

**Comment by gduscher** [comment]
Yes, sounds better.

**Comment by ssomnath** [comment]
rename_dimension() has indeed been implemented.
