### ISSUE TITLE
Improved API documentation

### ISSUE THREAD

**Issue by ssomnath** [pycroscopy/sidpy#20]
We would like to see the entire docstrings for each function. Currently, only a single line is visible for each function.

**Comment by ssomnath** [comment]
Follow @JamesALeedham's [example repository](https://github.com/JamesALeedham/Sphinx-Autosummary-Recursion) and his [instructions on StackOverflow](https://stackoverflow.com/questions/2701998/sphinx-autodoc-is-not-automatic-enough/62613202#62613202)

**Comment by ssomnath** [comment]
I started a new branch ``dev-docs`` following these guidelines. However, now I am getting a bunch of errors - sphinx apparently cannot find the submodules of sidpy for some reason. I think this may have to do with the fact that we have ``..autosummary`` directives at each ``init``. Not sure... @JamesALeedham - would you be able to guide?

**Comment by JamesALeedham** [comment]
I got your `dev-docs` to work for me locally after a bit of fiddling.

1) As you say, remove all the `.. autosummary` directives and hard-coded module refs inside """ comments in `__init__.py` files. There not causing the problem per se, but they are duplicating everything and are now completely unnecessary.
2) In `index.rst`, remove `.. currentmodule:: index`. It seems to be causing confusion.
3) In `conf.py`, comment out `sys.path.insert(0, os.path.abspath('../`)). I'm not quite sure why you don't need this, but it seemed to work once commented out.
4) In `custom-module-template.rst`, you need to add `:toctree` entries under `.. autosummary:` directives for both Attributes and Functions. Otherwise you won't get actual documentation pages for your many functions. As you've done for Classes and Exceptions.

In `Makefile`, I can recommend clearing your `_autosummary` and `build` caches each time you run `make html` as follows:
```
# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
        rm -rf build
        rm -rf source/_autosummary
        @$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
```

**Comment by JamesALeedham** [comment]
If you make the above changes and push to `dev-docs`, I can take another look... there's something not quite right here but I can't put my finger on it at the moment.

Sphinx is maddening like that.

**Comment by ssomnath** [comment]
@JamesALeedham - Thank you very much for helping! I have spent a LOT of time on Sphinx and haven't gotten anywhere nearly as far as you have...

I believe I have followed your instructions. It appears that you saw the branch just before I pushed some commits that seem to have addressed your fourth point. I just copied the templates from your repo.

However, still stuck. I wonder if this may have something to do with ``conf.py``. I have all the lines and values to match yours. However, I have other configurations that may be messing things up.

**Comment by ssomnath** [comment]
I used your ``conf.py``. Didn't help

Also, I removed the ``sys.path.append()`` in ``conf.py``. I then get:

Failed to import 'base': no module named base
Failed to import 'hdf': no module named hdf
Failed to import 'proc': no module named proc
Failed to import 'sid': no module named sid
Failed to import 'viz': no module named viz
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 6 source files that are out of date
updating environment: [new config] 12 added, 0 changed, 0 removed
reading sources... [100%] notebooks/01_parallel_computing/index                                                                                                                       
WARNING: autodoc: failed to import module 'base'; the following exception was raised:
No module named 'base'
WARNING: autodoc: failed to import module 'hdf'; the following exception was raised:
No module named 'hdf'
WARNING: autodoc: failed to import module 'proc'; the following exception was raised:
No module named 'proc'
WARNING: autodoc: failed to import module 'sid'; the following exception was raised:
No module named 'sid'
WARNING: autodoc: failed to import module 'viz'; the following exception was raised:
No module named 'viz'

**Comment by JamesALeedham** [comment]
In `index.rst`, add the name of the module, leaving a blank line:

```
.. autosummary::
   :toctree: _autosummary
   :template: custom-module-template.rst
   :recursive:

   sidpy
```

**Comment by JamesALeedham** [comment]
Pulling your latest `dev-docs` and adding the above works for me locally.

There **is** something odd going on in `conf.py`, not entirely sure what. You could try putting back:

`sys.path.insert(0, os.path.abspath('../..'))`

What this is supposed to be saying is "set the root of the API to document to be two directories up from the location of `conf.py`". It seems to work for me without that line, but it might be environmental.

**Comment by ssomnath** [comment]
So you are right. I did need to put back the ``sys.path.insert()``. I can now build the documentation successfully. It is a little sad that building documentation in the obvious / correct way feels like mastering black magic. We are very grateful for your help and support! Thank you very much!

**Comment by JamesALeedham** [comment]
You're welcome.

Hopefully it'll just work forever now and you won't have to worry about it.

**Comment by JamesALeedham** [comment]
PS. I did notice that you've got the API documented twice now... at the bottom of `basic.rst` there's a hard-coded `.. autosummary:` directive:

```
API Reference
=============

.. currentmodule:: sidpy

.. automodule:: sidpy
    :no-members:
    :no-inherited-members:

:py:mod:`sidpy`:

.. autosummary::
    :toctree: _autosummary/
    :template: module.rst

    sidpy.base
    sidpy.hdf
    sidpy.io
    sidpy.proc
    sidpy.sid
    sidpy.viz
```

I **think** what you want to do is remove the above, cut the following out of `index.rst`, and paste it into `basic.rst` instead:

.. autosummary::
   :toctree: _autosummary
   :template: custom-module-template.rst
   :recursive:

   sidpy

That way, the API will be documented where you want it to be in the table of contents...

**Comment by ssomnath** [comment]
I revised the index page to remove the duplication of the API documentation. Also, merged the documentation branch since it was working satisfactorily.
