### ISSUE TITLE
Sidpy Fitter save Fitting Function

### ISSUE THREAD

**Issue by ramav87** [pycroscopy/sidpy#200]
In the sippy fitter class, we should save the fitting function. We can do this by serializing the function with dill, before saving it to hdf5. Assuming the we got the fit_data from the fitter class, we can do:

```
import dill

# Create your dictionary
my_dictionary = {'my_function': SHO_fit_flattened}

# Serialize the functions in the dictionary using dill and encode as base64
encoded_dict = {}
for key, value in my_dictionary.items():
    serialized_value = dill.dumps(value)
    encoded_value = base64.b64encode(serialized_value).decode('utf-8')
    encoded_dict[key] = encoded_value

fit_data.metadata['fitting_function'] = encoded_dict #save to the metadata
```

Then to access the function again, we can do

```
fit_fn_packed = fit_data.metadata['fitting_function']
loaded_dict = {}
encoded_value = fit_fn_packed['my_function']
serialized_value = base64.b64decode(encoded_value)
loaded_dict[key] = dill.loads(serialized_value)
fit_fn = loaded_dict['my_function'] #retrieve the function

```

**Comment by ramav87** [comment]
This functionality has been added to the fitter_fn branch:

https://github.com/pycroscopy/sidpy/tree/fitter_fn

For reading the functions, I modified pyNSID: 

https://github.com/pycroscopy/pyNSID/tree/decode_functions

We need to heavily test both of these. Given interdependence between sidpy, SciFiReaders and pyNSID, this needs a careful look-through.

**Comment by utkarshp1161** [comment]
I will try to find out more about the failing tests.

**Comment by utkarshp1161** [comment]
Assertion failing at line 63(validate_dataset_properties function) in /Users/utkarshpratiush/project/sidpy_rama_branch/sidpy/tests/sid/test_dataset.py when executing test_fitter.py:  



Reason:
 there is an additional key "fitting_functions" within the dataset.metadata that is not present in the standalone metadata dictionary.
 
   metadata.keys(): dict_keys(['info_1', 'instrument', 'fit_parms_dict'])
   
   dataset.metadata.keys(): dict_keys(['info_1', 'instrument', 'fit_parms_dict', 'fitting_functions'])
 
 QHow do you suggest to handle this?

**Comment by utkarshp1161** [comment]
Addressed in :

https://github.com/pycroscopy/sidpy/commit/fbdc67bb5b18d4efa6803937056b1a05dc9c6ab3
