### ISSUE TITLE
Display scientifically relevant information when printing Datasets

### ISSUE THREAD

**Issue by ssomnath** [pycroscopy/sidpy#24]
We need to adopt / adapt what ``USIDataset.__repr__`` does for ``sidpy.Dataset``. Currently, printing the ``Dataset`` object just displays overly technical ``dask.array`` details such as the chunks, processes, etc. which are not really of interest to users. Instead / in addition, we need to be showcasing the dimensions, their names, shape of the dataset, name of the dataset, quantity, units etc. One thing we could do is let ``__repr__`` be something specific to ``sidpy``. We could have a ``print_darray`` or ``print_dask`` which would just call upon ``dask.array.__repr__``. Perhaps we could show that certain key attributes such as quantity, etc. even if they are set to "generic" just to encourage users to populate such key metadata instead of leaving everything as "generic"

**Comment by gduscher** [comment]
First try is implemented, everybody shoud check it out. 
Let us know if there is anything else needed.
