### ISSUE TITLE
Display hierarchical metadata in Dataset as a tree

### ISSUE THREAD

**Issue by ssomnath** [pycroscopy/sidpy#25]
It would be nice to be able to visualize the (typically) hierarchical metadata embedded within a Dataset in a clean manner. Perhaps this printing / visualization could take advantage of the core bits in ``sidpy.hdf.hdf_utils.print_tree()``. Perhaps, we would need to develop a function that visualizes a nested dictionary. Both ``sidpy.hdf.hdf_utils.print_tree()`` and ``sidpy.Dataset.view_metadata()`` could call upon this function.

**Comment by gduscher** [comment]
Added a view_metadata function to class.
Was all already done by Suhas in dict_utils, so I just used that.
