### ISSUE TITLE
Standard for capturing results of operations

### ISSUE THREAD

**Issue by ssomnath** [pycroscopy/sidpy#31]
On 8/28/2020 we agreed that:
1. Provenance capture is important
2. Provenance will only be captured within a single HDF5 file and not between files. Such applications will need a more comprehensive management system like [DataFed](https://datafed.ornl.gov)
3. Results of each run of an operation will be written to a new HDF5 group
4. The group would be named ``Op_AlgorithmName_00x``. The prefix is TBD
5. Given that we are not sure how well HDF5 supports attributes whose values are a list of HDF5 dataset references, we would store information regarding all source datasets as individual attributes:
   * ``source_dataset_000`` = ``<HDF5 Dataset reference>``
   * ``source_dataset_001`` = ``<HDF5 Dataset reference>`` ...
6. Metadata / context regarding the algorithm itself would be captured in a separate group within this new group that would allow metadata to be nested if need be. 

This information should be incorporated when addressing #15

**Comment by gduscher** [comment]
I think this should go possibly t.o pyUSID and pyNSID, because the dataset in sidpy lives only in "memory".
If we provide a function here for both "file formats" which are we using for the data?

Alternatively we could merge of pyNSID and sidpy which would make it clear in which format the results are saved.

**Comment by ssomnath** [comment]
You are right that sidpy is format agnostic. This is something that we'll bring up again once we have stable packages. 

You do have a valid point about merging pyNSID and sidpy. I would like to explore this once we see the interactions between the packages.

**Comment by gduscher** [comment]
Yes I think there is no rush, we just should keep it in mind.
Gerd
