### ISSUE TITLE
Dimension assertions in visualizer fail for USID Dimensions

### ISSUE THREAD

**Issue by rajgiriUW** [pycroscopy/sidpy#34]
Visualizer calls sidpy functions that assert/strict-test for ```sidpy.dimension.Dimension```, making it not backwards compatible (no warning given) with ```usid.dimension.Dimension```. I'm manually fixing for now, currently failing for ```USIDataset.visualize()``` on my data. 

File is ```viz.jupyter_utils.simple_ndim_visualizer```

Suggest soft-check with optional warning, since otherwise makes data pre-sidpy USID Dimensions fail when calling ```visualize```.

Alternatively USID shouldn't call sidpy's visualize and should have its own, but that seems messy.

**Comment by ssomnath** [comment]
This one is very much on my radar. I propose that ``pyUSID.Dimension`` extend ``sidpy.sid.Dimension`` this should minimize failure. Eventually, we will remove ``pyUSID.Dimension``. An [issue](https://github.com/pycroscopy/pyUSID/issues/48) is already open in pyUSID.

**Comment by ssomnath** [comment]
Also @rajgiriUW - we may want to potentially extend / adopt components of ``sidpy.Dataset`` in ``pyUSID.USIDataset``. This way, we could adopt @gduscher 's new visualization classes (much easier to debug and maintain in addition to be more pleasant to use) and slowly deprecate the existing behemoth of the ``viz.jupyter_utils.simple_ndim_visualizer``. What are your thoughts on all this?

**Comment by rajgiriUW** [comment]
That probably makes sense but I think I need to see what specifically changes in sidpy Dataset, I'm admittedly behind on looking through that. The new visualizer class works for me if I allow the assert to check for usid.Dimension instead of sidpy.Dimension, which means for what you say to work that line would still fail unless USIDataset is just replaced by sidy.Dataset, right?

**Comment by ssomnath** [comment]
Yes things would still fail. We don't want to do a hacky job. I will look into this tonight.

**Comment by ssomnath** [comment]
With the latest changes to the master branch on pyUSID, pyUSID and sidpy essentially use the same Dimension class that should prevent the ``USIDataset.visualize()`` from breaking. 

@rajgiriUW - Could you please check and close this issue if you feel that it has been addressed

**Comment by rajgiriUW** [comment]
@ssomnath Yeah I think this works.

**Comment by ssomnath** [comment]
Thanks @rajgiriUW !
