### ISSUE TITLE
conda forge recipe and installer

### ISSUE THREAD

**Issue by ssomnath** [pycroscopy/sidpy#37]
We need to get ``sidpy`` on conda forge. The process will be similar to that for ``pyUSID``. Perhaps, we need @carlodri to help / guide

**Comment by ssomnath** [comment]
Referencing [issue on hyperspy](https://github.com/hyperspy/hyperspy/issues/2495)

**Comment by carlodri** [comment]
yeah I can do that, I just need some days since I'm quite overwhelmed with family and work duties...

**Comment by ssomnath** [comment]
Thank you very much @carlodri . I fully understand. Please let me know how I can help

**Comment by ssomnath** [comment]
[Addressed](https://github.com/conda-forge/staged-recipes/pull/12554) thanks to @carlodri and @synapticarbors. Much appreciated!

**Comment by carlodri** [comment]
this can be closed, sidpy recipe is complete and pyusid has been updated
