### ISSUE TITLE
Dataset and dimension types to use Enum

### ISSUE THREAD

**Issue by ssomnath** [pycroscopy/sidpy#38]
We use strings to identify the types of Datasets such as ``image`` or ``image-stack``. It would be great to be able to use ``enum`` to coerce the types. For example an ``Image`` may not be interpreted as a ``image``. This will make it easier to assign a ``Visualizer`` for a given ``Dataset`` object. Speaking of which, do we need an abstract ``Visualizer`` class that all other existing classes extend?

**Comment by gduscher** [comment]
Is implemented now

**Comment by gduscher** [comment]
Is implemented NOW for Datasets and Dimensions!
