### ISSUE TITLE
Provide links to example notebooks in index.rst

### ISSUE THREAD

**Issue by ssomnath** [pycroscopy/sidpy#47]
Currently, the documentation lists the ``Basic`` and ``Parallel computing`` examples. Clicking on them shows a mostly empty page. We want to add links to the notebooks contained within each of those folders. 

@ziatdinovmax Do we need the README.rst?

**Comment by ziatdinovmax** [comment]
The #53 should address it.
I deleted README.rst from the folders with examples, as we do not need it unless we want to add some specific instructions about adding notebooks with examples for each folder/section.

**Comment by ssomnath** [comment]
Thanks @ziatdinovmax !
