### ISSUE TITLE
Clarify properties and best practices for Dataset

### ISSUE THREAD

**Issue by ssomnath** [pycroscopy/sidpy#48]
Docstrings of ``sidpy.Dataset`` (and example notebook) should clarify what should go into ``original_metadata``, ``metadata``, and other best practices for ``sidpy.Dataset``

**Comment by gduscher** [comment]
Started to include this in create_dataset notebook.

**Comment by ssomnath** [comment]
@gduscher - ``Dataset`` has a lot of attributes with no documentation. For example, I do not know what ``group_attrs`` means or the difference between ``attrs`` and ``metadata`` or between ``modality`` and ``data_type``. I have attempted to clarify as many of them as possible [here](https://pycroscopy.github.io/sidpy/_autosummary/sidpy.sid.dataset.Dataset.html#sidpy.sid.dataset.Dataset). Please correct the documentation where appropriate. Please remove unnecessary / redundant attributes if possible.

**Comment by ssomnath** [comment]
@gduscher - 
1. what is the difference between ``Dataset.like_data()`` and ``Dataset.copy()``. 
2. Shouldn't ``Dataset.get_extent()`` be internal? Also, I don't know how I would use it. Do you have an example for this?
3. Why don't ``metadata`` and ``original_metadata`` have setter and property functions?

**Comment by gduscher** [comment]
1. If you make an operation on a dataset, the dimensions and metadata are the same and so it is easy to make a new dataset with like_data. That works even when the size changes.
 A copy is just a deep copy of the Dataset.

2. get_extent should be used in matplotlib. So usage is encouraged.

3. good point, I agree these attributes should have setter and property functions.

**Comment by ssomnath** [comment]
1. Operations on the dataset will be the most complex thing we will need to do. For example, how will we handle reduction of a dimension, transpose, etc.? I think that we will need to extend every function allowed on a dataset and then appropriately adjust other properties of the Dataset...
2. Ok
3. Can you do this on the dev_gerd branch?

**Comment by gduscher** [comment]
1. Yes, so the like_data is a start in that direction.
3. will do.
