### ISSUE TITLE
Tests fail on 1-core machine

### ISSUE THREAD

**Issue by bmwiedemann** [pycroscopy/sidpy#59]
While working on [reproducible builds](https://reproducible-builds.org/) for [openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds), I found that our [`python-sidpy`](https://github.com/bmwiedemann/openSUSE/blob/master/packages/p/python-sidpy/python-sidpy.spec#L77) package fails tests on a 1-core VM

```
 tests/proc/test_comp_utils.py::TestParallelCompute::test_invalid_func_type PASSED [ 78%]
 tests/proc/test_comp_utils.py::TestParallelCompute::test_respect_requested_cores Number of CPU free cores set to: 1 given that the CPU has 1 logical cores.
 2 cores requested.
 Clipped explicit request for CPU cores to: 1
 computational jobs per core = 30. For short computations, each core must have at least 20 jobs to warrant parallel computation.
 Computations are not lengthy.
 Rank 0 starting computing on 1 cores (requested 2 cores)
 Rank 0 computing serially ...
```

https://github.com/jmcarpenter2/swifter/issues/102 solved a similar issue by skipping such tests when not enough cores were available.

to reproduce on openSUSE or Debian:
```bash
osc co openSUSE:Factory/python-sidpy && cd $_
osc build --vm-type=kvm -j1 --noservice standard
```

Maybe the issue can also be triggered via `taskset 1  pytest-3.8`

**Comment by ssomnath** [comment]
@bmwiedemann - thank you for raising this issue. I have added appropriate safeguards for single core computations. We will be pushing out a new version with these fixes very soon.

May I ask why ``sidpy`` is being included in ``OpenSUSE``?

**Comment by bmwiedemann** [comment]
> May I ask why `sidpy` is being included in `OpenSUSE`?

I am not the maintainer, but think it is probably because of [pyUSID](https://github.com/bmwiedemann/openSUSE/blob/480610fa4f89f03e60042c69372a97556cf22034/packages/p/python-pyUSID/python-pyUSID.spec#L56)

**Comment by ssomnath** [comment]
I see. Ok
