### ISSUE TITLE
colorbar implementation warning in plot_utils due to depreciation of Matplotlib

### ISSUE THREAD

**Issue by smisra87** [pycroscopy/sidpy#78]
Runing the following code snippet throws a warning:
Code snippet:
fig, axes = sidpy.plot_utils.plot_map_stack(raw_data_3d, reverse_dims=True, pad_mult=(0.15, 0.15),
                                           title='Spatial maps of current at different bias', stdevs=2,
                                           color_bar_mode='single', num_ticks=3, x_vec=x_vec, y_vec=y_vec,
                                           evenly_spaced=True, fig_mult=(3, 3), title_yoffset=0.95)

Warning:
MatplotlibDeprecationWarning: Since 3.2, mpl_toolkits's own colorbar implementation is deprecated; it will be removed two minor releases later.  Set the 'mpl_toolkits.legacy_colorbar' rcParam to False to use Matplotlib's default colorbar implementation and suppress this deprecation warning.
  cb = axes.cbar_axes[0].colorbar(im)

**Comment by ramav87** [comment]
Have gone through and set the rcParam to False as suggested. Available on rama_dev. This seems to suppress warnings, but not fully tested.
